"""config package."""

# Settings
from .settings import (
    APP_ENVIRONMENT,
    BASE_DIR,
    BATCH_SIZE,
    CHROMA_COLLECTION_NAME,
    DATA_DIR,
    DELIMITER_CHAR,
    DELIMITER_HEAVY,
    DELIMITER_LINE,
    DELIMITER_POPUP,
    DELIMITER_POPUP_LINE,
    DELIMITER_SECTION,
    DIRECTORY_PATHS,
    FILE_PATHS,
    LOG_DIR,
    LOG_LEVEL,
    MAX_LINE_LENGTH,
    MAX_RETRIES,
    OPENAI_API_KEY,
    OPENAI_EMBEDDING_MODEL,
    OPENAI_MAX_TOKENS,
    OPENAI_MODEL,
    REDIS_DB,
    REDIS_HOST,
    REDIS_PASSWORD,
    REDIS_PORT,
    REQUEST_TIMEOUT,
    TERMINAL_WIDTH,
    TLDV_API_KEY,
    TLDV_BASE_URL,
    TLDV_TIMEOUT,
)

# Startup
from .startup import (
    ensure_directories_exist,
    initialize_application,
    setup_logging,
)

__all__ = [
    "APP_ENVIRONMENT",
    "BASE_DIR",
    "BATCH_SIZE",
    "CHROMA_COLLECTION_NAME",
    "DATA_DIR",
    "DELIMITER_CHAR",
    "DELIMITER_HEAVY",
    "DELIMITER_LINE",
    "DELIMITER_POPUP",
    "DELIMITER_POPUP_LINE",
    "DELIMITER_SECTION",
    "DIRECTORY_PATHS",
    "FILE_PATHS",
    "LOG_DIR",
    "LOG_LEVEL",
    "MAX_LINE_LENGTH",
    "MAX_RETRIES",
    "OPENAI_API_KEY",
    "OPENAI_EMBEDDING_MODEL",
    "OPENAI_MAX_TOKENS",
    "OPENAI_MODEL",
    "REDIS_DB",
    "REDIS_HOST",
    "REDIS_PASSWORD",
    "REDIS_PORT",
    "REQUEST_TIMEOUT",
    "TERMINAL_WIDTH",
    "TLDV_API_KEY",
    "TLDV_BASE_URL",
    "TLDV_TIMEOUT",
    "ensure_directories_exist",
    "initialize_application",
    "setup_logging",
]
